sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pradeepyrl/docker-react-learning -f Dockerfile.dev .

script:
  - docker run -e CI=true pradeepyrl/docker-react-learning npm run test
